version: "3.8"

services:
    embed:
        ports:
            - 8181:8080
        build:
            context: ./slm-embed
        environment:
            - CONSUL_HOST=consul
        networks:
            - slm

    consul:
        image: consul:1.15.4
        ports:
            - "8500:8500"
            - "8600:8600/udp"
        environment:
            CONSUL_BIND_INTERFACE: eth0
        command: agent -server -bootstrap -ui -client=0.0.0.0 -datacenter=dc1 -node=consul-server
        networks:
            - slm

    postgres:
        image: postgres:15.4
        restart: always
        environment:
            POSTGRES_USER: slm
            POSTGRES_PASSWORD: slm123
            POSTGRES_DB: slm
        ports:
            - 5433:5432
        networks:
            - slm
networks:
    slm:
        driver: bridge
