version: "3.8"

services:
    embed:
        ports:
            - 8181:8080
        build:
            context: ./slm-embed
        networks:
            - slm

    postgres:
        image: postgres:15.4
        restart: always
        environment:
            POSTGRES_USER: slm
            POSTGRES_PASSWORD: slm123
            POSTGRES_DB: slm
        ports:
            - 5433:5432
        networks:
            - slm
networks:
    slm:
        driver: bridge
