spring:
  application:
    name: slm-backend
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/slm}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root123}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

security:
  jwt:
    secret-key: qwertyuiopasdfghjklzxcvbnmqwertyuiopaASDFGHJKLZXCVBNM123456
    expiration-time: 432000000  # Example: 5 days in milliseconds

embed-service:
  base-url: ${EMBED_HOST_API:http://localhost:8181}
  connection-timeout: 5000