spring:
  application:
    name: slm-embed
  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: 8500
      discovery:
        enabled: true
        register: true
        prefer-ip-address: true
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

management:
  endpoints:
    web:
      exposure:
        include: health

  datasource:
    hikari:
      maximum-pool-size: 1