spring:
  application:
    name: slm-embed
  servlet:
    multipart:
      max-file-size: 300MB
      max-request-size: 400MB

  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

  datasource:
    hikari:
      maximum-pool-size: 1